x-common-environment:
  &common-environment
  OLLAMA_MODEL_NAME: ${OLLAMA_MODEL_NAME:-qwen3:0.6b}
  OLLAMA_EMBEDDING_MODEL_NAME: ${OLLAMA_EMBEDDING_MODEL_NAME:-all-minilm:l6-v2}
  INFERENCE_DEPLOYMENT_NAME: ${INFERENCE_DEPLOYMENT_NAME:-ollama_chat/qwen3:0.6b}
  INFERENCE_BASE_URL: http://host.docker.internal:11434
  INFERENCE_API_KEY: ${INFERENCE_API_KEY:-t}
  EMBEDDINGS_DEPLOYMENT_NAME: ${EMBEDDINGS_DEPLOYMENT_NAME:-ollama/all-minilm:l6-v2}
  EMBEDDINGS_BASE_URL: http://host.docker.internal:11434
  EMBEDDINGS_API_KEY: ${EMBEDDINGS_API_KEY:-t}
  DEV_MODE: ${DEV_MODE:-True}
  FASTAPI_HOST: ${FASTAPI_HOST:-localhost}
  FASTAPI_PORT: ${FASTAPI_PORT:-8080}
  STREAMLIT_PORT: ${STREAMLIT_PORT:-8501}

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      # This allows access to the host's docker, e.g. for builds:
      - /var/run/docker.sock:/var/run/docker.sock
    command: make run-frontend
    ports:
      - "8501:8501"
    env_file: ".env.example.docker"
    environment:
      <<: *common-environment

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    command: make run-backend
#    ports:
#      - "8080:8080"
#    env_file: ".env.example.docker"
#    environment:
#      <<: *common-environment
