services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      # This allows access to the host's docker, e.g. for builds:
      - /var/run/docker.sock:/var/run/docker.sock
      - files:/kizlar-agha/files
    command: make run-frontend
    env_file: ".env"
    environment:
      POSTGRES_HOST: db

  db:
    image: postgres:${PG_MAJOR:-latest}
    container_name: postgres-db
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    env_file: ".env"
    environment:
      POSTGRES_HOST: db

volumes:
  files:
  postgres-data:
